infinum/qa-handbook

Testing/Testing - Web.md
Added `document.designMode='on'` to "Testing - Web"
=> Update Testing - Web.md

Basics/Stress and problems.md
Grammar fixes and simpler phrases put.
=> Edits for Stress and problems

Testing/Testing - Forms.md
Dodao sam 2 sekcije. Dosta toga je vec pokriveno i ima dovoljno informacija. Ako mislis da bi trebao dodat jos nesto. Samo reci.
=> Update Testing - Forms.md

Tools/Using TryOutApps.md
=> Update Using TryOutApps.md

Knowledge/QA glossary.md
dodano:
CMS - a content management system is computer software used to manage the creation and modification of digital content.
Jira-  a management tool for all kinds of use cases, from requirements and test case management to agile software development. 
Figma - a vector graphics editor and prototyping tool which is primarily web-based, with additional offline features enabled by desktop applications for macOS and Windows.
uklonio:
- Backlog
- Team weekly
- sve interne sastanke iz Q dijela (osim QA weekly)
Mormo provjeriti:
-  privatne Infinum servise 
=> Nebojsa glossary

Tools/Using Slack.md
Hej Matija my man :) 
Inspiraciju za ovaj clanak sam izvukao s ovog linka: https://slack.com/blog/collaboration/etiquette-tips-in-slack
Smjernice iz linka su jako slicne ali text sam prilagodio stilu pisanja u naseg Hanbooka. 
Ovo je prva verzija i mozemo je  izmijeniit kako god  želimo :)
=> Using Slack

Basics/Attending conferences.md
Ponovno sam uploadao .md file s obzirom da sam prvi stavio u krivi section u handbooku
=> Attending conferences.md upload

Basics/Attending conferences.md
Changelog:
Edited some minor mistakes in the text, corrected link for , removed some stuff and edited other
=> Update Attending conferences.md

Tools/Using Slack.md
provukao sam cijeli text kroz grammarly i hemingway i jedino sto sam nasao je par zareza koje je bilo potrebno ukloniti.
=> ispravak manjih gresaka

Testing/Testing - Testing session.md
Neven je lektorirao, ali provjeri ti još jednom.
=> Create Testing - Testing session.md

Automation/Locators.md
Naming differences updated.
Dodan i Note u Accessibility ID section.
=> Update automation locators

Automation/Mobile/qama.md
Updejtao qama članak.
Nisam išao u prevelike detalje jer sve ima u README-u te drugim člancima (na neke od njih sam se i referirao).
=> Update qama article

Basics/Working on projects.md, Testing/Heuristics in testing.md, Testing/Testing - Various.md, Testing/Testing - WordPress.md, Tools/Using Proxyman.md
Related to task Productive task: https://app.productive.io/1-infinum/tasks/task/2876078
Changes and updates were made to multiple articles.
=> Multiple handbook changes and improvements

Automation/Mobile/Troubleshooting Appium.md
Jos malo updejta.
Prilagodio errore.
=> Update Troubleshooting Appium article

Automation/Mobile/Appium/Troubleshooting Appium.md
Add additional solution for "Could not proxy command"
=> Update Troubleshooting Appium

Knowledge/QA glossary.md
=> PR for QA Glossary

Tools/Version Control Systems/Code management.md, Tools/Version Control Systems/Using Git - Advanced.md, Tools/Version Control Systems/Using Git - Basics.md
Related to task https://app.productive.io/1-infinum/tasks/3437736
Using Git articles were just slightly updated.
Code management article added. The idea is to briefly cover hosting services and focus more on those, rather than to have both e.g. git and GitHub info in once place. Those are not the same thing and should be separated.
=> Update git articles

Automation/Mobile/Appium/Appium setup.md
Fix code blocks appearance
Add bash example for updating env variables
=> Fix Appium setup

Automation/Way of working/Pull requests.md, Automation/Way of working/Version control.md
Updated the Version control article (removed PR section)
Added a standalone Pull requests article
https://app.productive.io/1-infinum/tasks/4305253
=> Pull requests

Automation/Python/Pytest tips & tricks.md
First version of the article.
The idea is to start with a few basic tips and then continue to expand the article with info we deem useful.
=> Add pytest tips & tricks article

Testing/Testing - Prerelease.md
Transfer "Google Play tracks" and "TestFlight tracks" sections to tables
=> update testing Prerelease

Automation/Python/Pytest tips & tricks.md
Updated Pytest tips & tricks with Fixtures and Hooks section.
=> Update Pytest tips & tricks.md

Basics/Impostor syndrome.md
Added "Impostor syndrome" chapter
=> impostor syndrome chapter added

Basics/Testing in general.md
=> update testing in general

Basics/Working on projects.md
update working on projects - A project's rhythm
=> update working on projects

Testing/Testing - WordPress.md
=> Update Testing - WordPress.md

Tools/Using Postman.md
Add just a short description about Postman flows and linked official Postman documentation.
=> Add Postman flow paragraf

Automation/Locators/General.md, Automation/Mobile/Appium/Troubleshooting Appium.md, Automation/Python/Pytest tips & tricks.md, Automation/Way of working/Test automation.md, Automation/Way of working/Working on a project.md
Minor changes:
- line breaks
- updated links
Updated Locators General - Accessibility ID section
=> Update automation articles

Automation/Way of working/Pull requests.md
Added blank line to fix indentation in the Pull Requests article.
https://beta.infinum.com/handbook/qa/automation/way-of-working/pull-requests
@endriina 
Pls check if this is ok, works on staging.
https://beta.infinum.com/handbook/qa/automation/way-of-working/pull-requests
=> Fix indentation

Tools/Using Chrome Dev Tools.md
Updated Lighthouse article (Section under `Tools > Using Chrome Dev Tools`) based on the comments from https://app.productive.io/1-infinum/tasks/7579131
Changes are available on Staging: https://beta.infinum.com/handbook/qa/tools/using-chrome-dev-tools#lighthouse
=> Lighthouse section update

Tools/General tool list.md
Added YT-DPL tool in the list of helpful tools.
=> Update of the General Tool list article
